### ISSUE TITLE
Question: Connect to scrcpy server and send commands

### ISSUE THREAD

**Issue by RazumeikoAlex** [Genymobile/scrcpy#1249]
Hi. First of all, thanks for such amazing app. It works really good.

I am writing python script which analyzes screen and depends on some events on the screen i need to send swipe events . My initial version was on ADB then socket to ADB server but it's slower than your version.

Currently i am using scrcpy to get live screen and i want to send events through scrcpy, i am trying to open socket connection to scrcpy server but no luck.
 Is it accessible? Is it right server address: `127.0.0.1:27183`? 
Do i need to do any specific actions to open socket connection with your server? I tried to learn how you do it but it looks like you just open LocalSocket by name and that's it, maybe there is limit on number of connections?
Also if it's possible to reuse your connection, could you point please, quick example how to build request to do input action? swipe for example.

Thanks.

**Comment by rom1v** [comment]
The whole thread #129 should help you.

**Comment by RazumeikoAlex** [comment]
@rom1v i checked it and tried to repeat it but looks like it's little bit different from what i need. In example  he run server separately on mobile but i need to run regular client + server + my script. 

When i tried to forward internal port and connect i receive empty string in response but connected succesfully, when i try to connect to same port as scrcpy do, i receive timeout, it looks like server can't handle multiple connections?

**Comment by RazumeikoAlex** [comment]
I just realized that i don't need client running, i can get everything from server, i was trying to run server with 
```
adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.12 0 8000000 30 true
```
But i get "Aborted" all the time. Tried to play with arguments but now luck. I am on Android Q, Pixel 3a, is this something with access rights? How can i debug it?

**Comment by RazumeikoAlex** [comment]
It turns out that server file removed after run and i had wrong params. Fixed now and server works. Thanks!

**Comment by rxydenxd** [comment]
> It turns out that server file removed after run and i had wrong params. Fixed now and server works. Thanks!

(noob alert) can you tell me what were the wrong parameters?

**Comment by razumeiko** [comment]
@rxydenxd in new versions of server there are more params, here is my final code 
`com.genymobile.scrcpy.Server 1.12.1 1024 8000000 30 true - false true'

**Comment by rxydenxd** [comment]
copied your code `com.genymobile.scrcpy.Server 1.12.1 1024 8000000 30 true - false true` still no luck. how to find what parameters are right for me?

**Comment by razumeiko** [comment]
@rxydenxd i was looking at source code of server and checking what arguments it takes.

**Comment by rxydenxd** [comment]
> It turns out that server file removed after run

I guess it has something to do with this?

**Comment by razumeiko** [comment]
@rxydenxd you are using python for getting this work?

**Comment by rxydenxd** [comment]
> @rxydenxd you are using python for getting this work?

yes brother

**Comment by rom1v** [comment]
>     adb server version (39) doesn't match this client (41); killing...

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions

**Comment by razumeiko** [comment]
@rxydenxd you can check usage example here https://github.com/razumeiko/py-android-viewer
