### ISSUE TITLE
scrcpy and Force Touch Detector conflict (xposed plugin)

### ISSUE THREAD

**Issue by liangjinghao** [Genymobile/scrcpy#2125]
scrcpy 和 Force Touch Detector 冲突，会使点击操作变成大面积按压。

The conflict between scrcpy and Force Touch Detector will make the click operation become a large area pressing.

- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
I don't know "Force touch detector".

scrcpy just injects a click event at the requested position: https://github.com/Genymobile/scrcpy/blob/f8524a2be738e6471ed2e48265f2663d8c21c0be/server/src/main/java/com/genymobile/scrcpy/Controller.java#L174

**Comment by gaussandhisgun** [comment]
https://github.com/tkgktyk/ForceTouch this is the Force Touch Detector this is about.

**Comment by gaussandhisgun** [comment]
actually, this is the reason (watch the top-right): https://imgur.com/a/aymvorN
first screenshot is me swiping with my finger on my device screen. as my screen is broken, it always gives me size of 0.0, but on my older phone this number is bigger, the more of my finger actually touches the screen. and scrcpy for some reason sends a perfect 1.0 which means THE ENTIRE SCREEN is one touch point. force touch detector is mapped to see this changes and act differently if touch area (Size) is more than a certain value, and 1.0 is clearly more than ANY of physically possible values.

**Comment by rom1v** [comment]
> scrcpy for some reason sends a perfect 1.0

Hmm, indeed:

https://github.com/Genymobile/scrcpy/blob/f8524a2be738e6471ed2e48265f2663d8c21c0be/server/src/main/java/com/genymobile/scrcpy/Controller.java#L48

> For a touch screen or touch pad, reports the approximate size of the contact area in relation to the maximum detectable size for the device. The value is normalized to a range from 0 (smallest detectable size) to 1 (largest detectable size), although it is not a linear scale.

https://developer.android.com/reference/android/view/MotionEvent#AXIS_SIZE

Try with:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Controller.java b/server/src/main/java/com/genymobile/scrcpy/Controller.java
index 84780239..d8059b43 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Controller.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Controller.java
@@ -45,7 +45,7 @@ public class Controller {
 
             MotionEvent.PointerCoords coords = new MotionEvent.PointerCoords();
             coords.orientation = 0;
-            coords.size = 1;
+            coords.size = 0;
 
             pointerProperties[i] = props;
             pointerCoords[i] = coords;
```diff

**Comment by rom1v** [comment]
Does it work better?

**Comment by liangjinghao** [comment]
> Does it work better?

我不是开发者，我不知道如何解决，scrcpy会在后面的版本更新后解决这个问题吗？
I am not a developer, and I don’t know how to solve it. Will scrcpy solve this problem after a later version update?

**Comment by rom1v** [comment]
Here is a server with the change (replace it in your v1.17 release):

 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2125/1/scrcpy-server)  
   _SHA256: b4b47837feb0704c07617316a398c48b383a700635032d351ab0d72606887fca_

**Comment by liangjinghao** [comment]
> Here is a server with the change (replace it in your v1.17 release):
> 
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2125/1/scrcpy-server)
>   _SHA256: b4b47837feb0704c07617316a398c48b383a700635032d351ab0d72606887fca_

非常感谢！
替换 v1.17版本的scrcpy-server后解决了问题，现在不会被识别为大面积的点击事件。

但我有另一个问题未解决，不知道是不是只有我有这种情况，还是使用方法发生了改变，v1.11版可以正常识别鼠标的点击为屏幕的触摸操作，但之后版本（v1.14,v1.16,v1.17)都会识别为触摸长按动作。

Thank you very much!
After replacing the scrcpy-server of v1.17 version, the problem was solved. Now it will not be recognized as a large area click event.

But I have another problem that is unresolved. I don’t know if it’s just me, or the method of use has changed. The v1.11 version can recognize the mouse click as a touch operation on the screen, but the later version (v1.14 ,v1.16,v1.17) will be recognized as a touch and long press action.

Environment

OS:  Windows10
scrcpy version: v1.17
phone model:redmi note5
phone OS:Havoc 3.12 (aosp)
Android version:10

**Comment by liangjinghao** [comment]
补充一个在特定应用（ExDialer）上的使用区别：
v1.11版可以正常点击拨号，但之后版本（v1.14,v1.16,v1.17)都不能拨号。

Supplement the use difference on a specific application (ExDialer):
The v1.11 version can normally click to dial, but later versions (v1.14, v1.16, v1.17) can not dial.

ExDialer packagename:com.modoohut.dialer

https://drive.google.com/file/d/1bV3WzJY-txIEMUPgdjagOHJkTtkK7fhX/view?usp=sharing

Force Touch Detector packagename:jp.tkgktyk.xposed.forcetouchdetector

https://drive.google.com/file/d/1lX8qLMQVCWcl48WAk41coVQs0rDC5iTg/view?usp=sharing

![22](https://user-images.githubusercontent.com/22400954/109825396-c0f0f700-7c74-11eb-93f9-550e726c014a.png)

**Comment by rom1v** [comment]
> The v1.11 version can normally click to dial, but later versions (v1.14, v1.16, v1.17) can not dial.

Could you test v1.12 and v1.13, please? (This will help to find the cause)

**Comment by liangjinghao** [comment]
> > The v1.11 version can normally click to dial, but later versions (v1.14, v1.16, v1.17) can not dial.
> 
> Could you test v1.12 and v1.13, please? (This will help to find the cause)

v1.11鼠标点击操作正常，拨号器（ExDialer）拨号正常。
v1.12,v1.121,v1.13鼠标点击识别为长按操作，拨号器（ExDialer）不能正常拨号。
测试版本全部均为scrcpy-win64 版本。

v1.11 The mouse click operation is normal, and the dialer (ExDialer) dials normally.
v1.12, v1.121, v1.13 mouse clicks are recognized as long-press operations, and the dialer (ExDialer) cannot dial normally.
All test versions are scrcpy-win64 versions.

**Comment by rom1v** [comment]
So the change has been introduced in v1.12. Here are the release notes: https://github.com/Genymobile/scrcpy/releases/tag/v1.12

I guess it's 26529d377fe8aae2fd1ffa91405aa801a0ce8a57 (related to #962).

**Comment by liangjinghao** [comment]
> So the change has been introduced in v1.12. Here are the release notes: https://github.com/Genymobile/scrcpy/releases/tag/v1.12
> 
> I guess it's [26529d3](https://github.com/Genymobile/scrcpy/commit/26529d377fe8aae2fd1ffa91405aa801a0ce8a57) (related to #962).

我不能自己处理这个问题，
你会在以后的版本更新中修复吗？
包含点击识别为大面积触摸和点击识别为长按以及拨号器点击不起作用的问题。

I can't handle this problem by myself,
Will you fix it in a future version update?
Contains the problem that the click is recognized as a large-area touch and the click is recognized as a long press and the dialer click does not work.

**Comment by rom1v** [comment]
> Will you fix it in a future version update?

The "large-area touch" fix is merged on `dev`: 218636dc1045d17c8c58e08cda5961a5a83a7281
For the other problem, I won't revert the fix for #962, your problem seems very specific to your device/environment.

You could try to [BUILD](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) `scrcpy` and try to revert 26529d377fe8aae2fd1ffa91405aa801a0ce8a57.

**Comment by liangjinghao** [comment]
> > Will you fix it in a future version update?
> 
> The "large-area touch" fix is merged on `dev`: [218636d](https://github.com/Genymobile/scrcpy/commit/218636dc1045d17c8c58e08cda5961a5a83a7281)
> For the other problem, I won't revert the fix for #962, your problem seems very specific to your device/environment.
> 
> You could try to [BUILD](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) `scrcpy` and try to revert [26529d3](https://github.com/Genymobile/scrcpy/commit/26529d377fe8aae2fd1ffa91405aa801a0ce8a57).

我的几个设备上使用都有这种情况，可能设备太老旧了，但自行构建对我来说有点难，可以为我修复v1.11的大面积触摸问题吗？给我v1.11的替换文件scrcpy-server。
感谢！

This is the case on several of my devices. Maybe the device is too old, but it is a bit difficult for me to build it by myself. Can you fix the large-area touch problem of v1.11 for me? Give me the replacement file scrcpy-server for v1.11.
thank!

**Comment by rom1v** [comment]
To confirm the cause of the problem, I applied this change to v1.17:
```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Controller.java b/server/src/main/java/com/genymobile/scrcpy/Controller.java
index 84780239..3d3e345e 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Controller.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Controller.java
@@ -14,7 +14,7 @@ import java.util.concurrent.TimeUnit;
 
 public class Controller {
 
-    private static final int DEVICE_ID_VIRTUAL = -1;
+    private static final int DEVICE_ID_VIRTUAL = 0;
 
     private static final ScheduledExecutorService EXECUTOR = Executors.newSingleThreadScheduledExecutor();
 
```
- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2125/2/scrcpy-server)
  _SHA256: 9769d18154767fbd0423b61586357d95cf5e290dca7092ebf8c5160f52a8dc7b_

**Comment by liangjinghao** [comment]
> To confirm the cause of the problem, I applied this change to v1.17:
> 
> ```diff
> diff --git a/server/src/main/java/com/genymobile/scrcpy/Controller.java b/server/src/main/java/com/genymobile/scrcpy/Controller.java
> index 84780239..3d3e345e 100644
> --- a/server/src/main/java/com/genymobile/scrcpy/Controller.java
> +++ b/server/src/main/java/com/genymobile/scrcpy/Controller.java
> @@ -14,7 +14,7 @@ import java.util.concurrent.TimeUnit;
>  
>  public class Controller {
>  
> -    private static final int DEVICE_ID_VIRTUAL = -1;
> +    private static final int DEVICE_ID_VIRTUAL = 0;
>  
>      private static final ScheduledExecutorService EXECUTOR = Executors.newSingleThreadScheduledExecutor();
>  
> ```
> 
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2125/2/scrcpy-server)
>   _SHA256: 9769d18154767fbd0423b61586357d95cf5e290dca7092ebf8c5160f52a8dc7b_

Thank you!
But this file only fixes the problem that the click is repaired as a long press, and it does not fix the problem of recognition as a large area touch.

> To confirm the cause of the problem, I applied this change to v1.17:
> 
> ```diff
> diff --git a/server/src/main/java/com/genymobile/scrcpy/Controller.java b/server/src/main/java/com/genymobile/scrcpy/Controller.java
> index 84780239..3d3e345e 100644
> --- a/server/src/main/java/com/genymobile/scrcpy/Controller.java
> +++ b/server/src/main/java/com/genymobile/scrcpy/Controller.java
> @@ -14,7 +14,7 @@ import java.util.concurrent.TimeUnit;
>  
>  public class Controller {
>  
> -    private static final int DEVICE_ID_VIRTUAL = -1;
> +    private static final int DEVICE_ID_VIRTUAL = 0;
>  
>      private static final ScheduledExecutorService EXECUTOR = Executors.newSingleThreadScheduledExecutor();
>  
> ```
> 
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2125/2/scrcpy-server)
>   _SHA256: 9769d18154767fbd0423b61586357d95cf5e290dca7092ebf8c5160f52a8dc7b_

谢谢！
但是这个文件只修复了点击识别为长按的问题，没有修复识别为大面积触摸的问题。

Thank you!
But this file only fixes the problem that the click is recognized as a long press, and does not fix the problem of recognition as a large-area touch

**Comment by rom1v** [comment]
I might merge d9786c6f7cfa547839df8ade4be01f5614cd5905 into `dev`.

Here are binaries for this branch (to be replaced in v1.17 release):

- [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2125/3/scrcpy.exe)
  _SHA256: eaf3033a76d41572d99222fb1ca0ce5337cccdafe84330b2dad13b6fb1c2737d_
- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2125/3/scrcpy-server)
  _SHA256: e19182a8e8b68b58865c4de7764e54aa30328c2edbdc8a9877e0d81ae5cb6198_

**Comment by liangjinghao** [comment]
> I might merge [`device_id_0`](https://github.com/Genymobile/scrcpy/commit/device_id_0) into .`dev`
> 
> Here are binaries for this branch (to be replaced in v1.17 release):
> 
> * [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2125/3/scrcpy.exe)
>   _SHA256: eaf3033a76d41572d99222fb1ca0ce5337cccdafe84330b2dad13b6fb1c2737d_
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2125/3/scrcpy-server)
>   _SHA256: e19182a8e8b68b58865c4de7764e54aa30328c2edbdc8a9877e0d81ae5cb6198_

完美，现在在我的手机上一切正常。
非常感谢你仍在为我提供支持！🤞

Perfect, everything works fine on my phone now.
Thank you very much for supporting me all the time!🤞

**Comment by rom1v** [comment]
Merged into `dev`.
