### ISSUE TITLE
scrcpy closes itself. Sometimes.

### ISSUE THREAD

**Issue by Azuite** [Genymobile/scrcpy#281]
scrcpy starts normally and I am able to use it but sometimes this happens and it closes

```
scrcpy-server.jar: 1 file pushed. 3.0 MB/s (18570 bytes in 0.006s)
INFO: Initial texture: 480x272
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
[h264 @ 00000000026ecf80] Invalid level prefix
[h264 @ 00000000026ecf80] error while decoding MB 15 8
[h264 @ 00000000026ecf80] concealing 304 DC, 304 AC, 304 MV errors in P frame
WARN: Cannot terminate server
```

**Comment by rom1v** [comment]
Interesting, it seems the server had a problem. Are there any relevant logs in the output of `adb logcat` when this happens?

On which device does this occur?

**Comment by rom1v** [comment]
@Azuite Also see #283.

**Comment by kr898** [comment]
Initial setup:  Was using front PC USB 2.0

Error occurred:
```
scrcpy-server.jar: 1 file pushed. 0.6 MB/s (19342 bytes in 0.032s)
INFO: Initial texture: 720x1280
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
[h264 @ 000000000261cd00] corrupted macroblock 5 31 (total_coeff=-1)
[h264 @ 000000000261cd00] error while decoding MB 5 31
[h264 @ 000000000261cd00] concealing 2249 DC, 2249 AC, 2249 MV errors in P frame
WARN: Cannot terminate server
```
Trying to get it working back had an error:
```
adb: error: failed to get feature set: device offline
ERROR: "adb push" returned with value 1
```

Fixed: Changed the USB port behind PC directly from the motherboard
High possibility there was not enough power on the front USB port.

Thanks @rom1v for Scrcpy! Much better than Visor!

**Comment by Azuite** [comment]
I was using Oppo R9.

It seems my problem is the same as @kr898. I will try using the USB port from my computer and see what happens. 

Unfortunately I don't have the log of when it happened. The problem didn't occur when I'm using it in Virtual Box and it was running throughout the whole night and only occurs when I use it on my com sometimes.

**Comment by haytham-med** [comment]
When devive is offline, that means you didnot disconnect adb, you need to disconnect after the session to avoid offline problems.

**Comment by aoy1** [comment]
> 有趣的是，服务器似乎有问题。`adb logcat`发生这种情况时，输出中是否有相关日志？
> 
> 这在哪台设备上发生？



> Interesting, it seems the server had a problem. Are there any relevant logs in the output of `adb logcat` when this happens?
> 
> On which device does this occur?



> @Azuite Also see #283.



> Interesting, it seems the server had a problem. Are there any relevant logs in the output of `adb logcat` when this happens?
> 
> On which device does this occur?

Help, amd's cpu,scrcpy closes itself. Sometimes.

**Comment by fdaf11** [comment]
@rom1v I Try, but Still Crash; and i think it is this problem:
