### ISSUE TITLE
Virtual display crashes on QPR1 Beta 3

### ISSUE THREAD

**Issue by aliantonio** [Genymobile/scrcpy#6234]
When trying to create virtual display, scrcpy crashes on latest QPR1 beta. 

<img width="1107" height="476" alt="Image" src="https://github.com/user-attachments/assets/1985b815-9a4c-4058-bbb6-7435a59b65ef" />

**Comment by rom1v** [comment]
Please post your framework.jar:

```
adb pull /system/framework/framework.jar
```

**Comment by aliantonio** [comment]
> Please post your framework.jar:
> 
> ```
> adb pull /system/framework/framework.jar
> ```

[framework.zip](https://github.com/user-attachments/files/21316666/framework.zip)

**Comment by rom1v** [comment]
A new method has been added to `IDisplayWindowListener.aidl` by [73c5007170c3398981f7d800bc81e6258dd317e7](https://android.googlesource.com/platform/frameworks/base.git/+/73c5007170c3398981f7d800bc81e6258dd317e7%5E%21/).

I think something like this should fix it:

```diff
diff --git server/src/main/aidl/android/view/IDisplayWindowListener.aidl server/src/main/aidl/android/view/IDisplayWindowListener.aidl
index 2b3311758..5f80ee0d2 100644
--- server/src/main/aidl/android/view/IDisplayWindowListener.aidl
+++ server/src/main/aidl/android/view/IDisplayWindowListener.aidl
@@ -63,4 +63,9 @@ oneway interface IDisplayWindowListener {
      * Called when the keep clear ares on a display have changed.
      */
     void onKeepClearAreasChanged(int displayId, in List<Rect> restricted, in List<Rect> unrestricted);
+
+    /**
+     * Called when the eligibility of the desktop mode for a display have changed.
+     */
+    void onDesktopModeEligibleChanged(int displayId);
 }
diff --git server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayWindowListener.java server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayWindowListener.java
index f2ecb158d..ce0ff6c64 100644
--- server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayWindowListener.java
+++ server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayWindowListener.java
@@ -36,4 +36,9 @@ public class DisplayWindowListener extends IDisplayWindowListener.Stub {
     public void onKeepClearAreasChanged(int displayId, List<Rect> restricted, List<Rect> unrestricted) {
         // empty default implementation
     }
+
+    @Override
+    public void onDesktopModeEligibleChanged(int displayId) {
+        // empty default implementation
+    }
 }
```

Here is a binary to replace in scrcpy 3.3.1:
- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/6234/1/scrcpy-server) <sub>`SHA-256: a82ff53dff4232748078c63a58b35dbe1a4e33f675a2778c2ff4988c6fe71a7`</sub>

---

However, I'd like to find a more permanent solution to this issue of functions being added to this `IDisplayWindowListener.aidl`.

**Comment by aliantonio** [comment]
Thanks for taking a look. Unfortunately it's still crashing for me with the same error using the updated binary.

**Comment by rom1v** [comment]
> Unfortunately it's still crashing for me with the same error using the updated binary.

OK, I saw a change in AOSP and assumed it was the cause. In fact there are other new methods (not published yet in AOSP):

<details><summary>diff</summary>

```diff
diff --git server/src/main/aidl/android/view/IDisplayWindowListener.aidl server/src/main/aidl/android/view/IDisplayWindow
Listener.aidl
index 2b3311758..3e664e813 100644
--- server/src/main/aidl/android/view/IDisplayWindowListener.aidl
+++ server/src/main/aidl/android/view/IDisplayWindowListener.aidl
@@ -63,4 +63,12 @@ oneway interface IDisplayWindowListener {
      * Called when the keep clear ares on a display have changed.
      */
     void onKeepClearAreasChanged(int displayId, in List<Rect> restricted, in List<Rect> unrestricted);
+
+    /**
+     * Called when the eligibility of the desktop mode for a display have changed.
+     */
+    void onDesktopModeEligibleChanged(int displayId);
+
+    void onDisplayAddSystemDecorations(int displayId);
+    void onDisplayRemoveSystemDecorations(int displayId);
 }
diff --git server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayWindowListener.java server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayWindowListener.java
index f2ecb158d..b8b00e447 100644
--- server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayWindowListener.java
+++ server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayWindowListener.java
@@ -36,4 +36,19 @@ public class DisplayWindowListener extends IDisplayWindowListener.Stub {
     public void onKeepClearAreasChanged(int displayId, List<Rect> restricted, List<Rect> unrestricted) {
         // empty default implementation
     }
+
+    @Override
+    public void onDesktopModeEligibleChanged(int displayId) {
+        // empty default implementation
+    }
+
+    @Override
+    public void onDisplayAddSystemDecorations(int displayId) {
+        // empty default implementation
+    }
+
+    @Override
+    public void onDisplayRemoveSystemDecorations(int displayId) {
+        // empty default implementation
+    }
 }
```

</details>

Please test with this new binary:

- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/6234/2/scrcpy-server) <sub>`SHA-256: af812307dcbdc4a1aba5cc9464efda82419b3d7d1f9cf035fb89fe69565f67b`</sub>

**Comment by aliantonio** [comment]
> > Unfortunately it's still crashing for me with the same error using the updated binary.
> 
> OK, I saw a change in AOSP and assumed it was the cause. In fact there are other new methods (not published yet in AOSP):
> 
> diff
> Please test with this new binary:
> 
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/6234/2/scrcpy-server) `SHA-256: af812307dcbdc4a1aba5cc9464efda82419b3d7d1f9cf035fb89fe69565f67b`

New binary got it working again. Taskbar doesn't appear or doesn't work when it does appear, but that's completely fine since freeform windows wasn't working anyway prior to beta 3. Thank you!

**Comment by heDuke** [comment]
The same problem appeared in Android Canary 2507

<img width="1013" height="351" alt="Image" src="https://github.com/user-attachments/assets/5801e184-ef3a-4305-a9bc-76efc59949fe" />

[framework.zip](https://github.com/user-attachments/files/21580850/framework.zip)

**Comment by rom1v** [comment]
@heDuke Does the provided binary solve your problem?

**Comment by heDuke** [comment]
No test yet,

**Comment by heDuke** [comment]
still crash

**Comment by heDuke** [comment]
and same problem happened

**Comment by heDuke** [comment]
<img width="1362" height="227" alt="Image" src="https://github.com/user-attachments/assets/2f505c63-6abd-4659-b936-ff44b1c88035" />

**Comment by rom1v** [comment]
You're still using scrcpy-server from scoop.

Set the `SCRCPY_SERVER_PATH` environment variable to the path where you downloaded the patchef scrcpy-server.

Or download the official release and replace scrcpy-server directly.

**Comment by heDuke** [comment]
<img width="1095" height="311" alt="Image" src="https://github.com/user-attachments/assets/266ef551-278d-4dd7-be4a-50fac655e3d1" />

I have uninstalled the scrcpy from scoop and used the official release,replacing scrcpy-server,but still crash.

**Comment by rom1v** [comment]
This one: https://github.com/Genymobile/scrcpy/issues/6234#issuecomment-3092203502 ?

(not the one a few comments before)

**Comment by heDuke** [comment]
yes

**Comment by heDuke** [comment]
Sorry bro, I just realized I made a mistake.

**Comment by rom1v** [comment]
Fixed in scrcpy 3.3.2. 🚀
