### ISSUE TITLE
Can not turn screen off in android Q with 1.10 scrcpy

### ISSUE THREAD

**Issue by vivian27** [Genymobile/scrcpy#835]
My device is Oneplus 7 pro with OxygenOS Android Q openbeta 2. I found ctrl + o cannot turnoff the screen of my device, and program carshed with following:

>INFO: Initial texture: 1440x3120
>[server] ERROR: Exception on thread Thread[Thread-1,5,main]
>java.lang.AssertionError: java.lang.reflect.InvocationTargetException
>        at >com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:96)
>        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:165)
>        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)
>        at com.genymobile.scrcpy.Controller.control(Controller.java:73)
>        at com.genymobile.scrcpy.Server$1.run(Server.java:45)
>        at java.lang.Thread.run(Thread.java:919)
>Caused by: java.lang.reflect.InvocationTargetException
>        at java.lang.reflect.Method.invoke(Native Method)
>        at >com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:94)
>        ... 5 more
>Caused by: java.lang.IllegalArgumentException: displayToken must not be null
>        at android.view.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:1523)
>        ... 7 more

scrcpy --version shows:

> scrcpy 1.10
>
>dependencies:o
> - SDL 2.0.10
> - libavcodec 58.35.100
> - libavformat 58.20.100
> - libavutil 56.22.100

So I noticed you had fixed this issues, but it seems don't work to me...

**Comment by agsola** [comment]
I'm having this issue since latest Android 10 update --> Android 10.0.0 (Release 3) - QP1A.190711.020.C3

When I turn on scrcpy, it shows this:
INFO: Initial texture: 1080x2248
[server] ERROR: Exception on thread Thread[Thread-1,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:96)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:165)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)
        at com.genymobile.scrcpy.Controller.control(Controller.java:73)
        at com.genymobile.scrcpy.Server$1.run(Server.java:45)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:94)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:1520)
        ... 7 more

And..., not only the screen doesn't turn off, but I cannot use the mobile from the computer. It just reflects the mobile screen, but slows the mobile down.

**Comment by rom1v** [comment]
> And..., not only the screen doesn't turn off, but I cannot use the mobile from the computer.

(The exception you get crashes the controller thread, so it is not surprising.)

**Comment by rom1v** [comment]
My device just received the Android 10 upgrade tonight, so I fixed the issue on `dev` branch: c33a147fd0e9fbd3a5add6f0190eea909d74c26d

**Comment by Ripple-Peng** [comment]
Excuse me, do you have a compiled version of windows that has fixed this problem？

**Comment by Ripple-Peng** [comment]
> My device just received the Android 10 upgrade tonight, so I fixed the issue on `dev` branch: [c33a147](https://github.com/Genymobile/scrcpy/commit/c33a147fd0e9fbd3a5add6f0190eea909d74c26d)

Excuse me, can you add a compiled version of windows that has fixed this problem?

**Comment by crazyserb** [comment]
Is there a compiled Windows version of this with this issue fixed?

I'm still experiencing this on v1.13.

**Comment by rom1v** [comment]
Could you paste the error you get in the console  please?

**Comment by crazyserb** [comment]
> Could you paste the error you get in the console please?

I did, here:

https://github.com/Genymobile/scrcpy/issues/1409
